In [1]:
import pandas as pd

In [4]:
data=pd.read_csv(r"C:\Users\nandh\Downloads\Instagram_fake_profile_dataset.csv")
data

profile pic  nums/length username  fullname words  nums/length fullname  \
0               1              0.270000               0              0.000000   
1               1              0.000000               2              0.000000   
2               1              0.100000               2              0.000000   
3               1              0.000000               1              0.000000   
4               1              0.000000               2              0.000000   
...           ...                   ...             ...                   ...   
4995            0              0.258135               0              0.000000   
4996            0              0.511986               1              0.000000   
4997            0              0.473108               1              0.353231   
4998            0              0.293326               1              0.000000   
4999            0              0.605471               1              0.016533   

      name==username  description length  external URL  private  #posts  \
0                  0                  53             0        0      32   
1                  0                  44             0        0     286   
2                  0                   0             0        1      13   
3                  0                  82             0        0     679   
4                  0                   0             0        1       6   
...              ...                 ...           ...      ...     ...   
4995               0                   0             0        1       7   
4996               0                   0             0        0       0   
4997               0                   0             0        0       0   
4998               0                   0             0        0      75   
4999               0                   1             0        0       0   

      #followers  #follows  fake  
0           1000       955     0  
1           2740       533     0  
2            159        98     0  
3            414       651     0  
4            151       126     0  
...          ...       ...   ...  
4995           1       217     1  
4996          51        24     1  
4997          20         0     1  
4998        1314      5120     1  
4999          57       344     1  

[5000 rows x 12 columns]

In [5]:
data.describe()

profile pic  nums/length username  fullname words  \
count  5000.000000           5000.000000     5000.000000   
mean      0.598200              0.166175        1.212800   
std       0.490311              0.194733        0.890435   
min       0.000000              0.000000        0.000000   
25%       0.000000              0.000000        1.000000   
50%       1.000000              0.089193        1.000000   
75%       1.000000              0.300410        2.000000   
max       1.000000              0.920000       12.000000   

       nums/length fullname  name==username  description length  external URL  \
count           5000.000000     5000.000000         5000.000000   5000.000000   
mean               0.036068        0.007600           20.997200      0.049600   
std                0.106235        0.086855           33.234706      0.217139   
min                0.000000        0.000000            0.000000      0.000000   
25%                0.000000        0.000000            0.000000      0.000000   
50%                0.000000        0.000000            1.000000      0.000000   
75%                0.000000        0.000000           31.250000      0.000000   
max                1.000000        1.000000          150.000000      1.000000   

           private       #posts    #followers     #follows        fake  
count  5000.000000  5000.000000  5.000000e+03  5000.000000  5000.00000  
mean      0.227800   103.331400  5.124435e+04   481.381800     0.50000  
std       0.419455   377.804886  5.963749e+05   761.530132     0.50005  
min       0.000000     0.000000  0.000000e+00     0.000000     0.00000  
25%       0.000000     0.000000  4.000000e+01    58.000000     0.00000  
50%       0.000000    10.000000  1.450000e+02   242.000000     0.50000  
75%       0.000000    81.000000  6.960000e+02   591.000000     1.00000  
max       1.000000  7389.000000  1.533854e+07  7500.000000     1.00000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   profile pic           5000 non-null   int64  
 1   nums/length username  5000 non-null   float64
 2   fullname words        5000 non-null   int64  
 3   nums/length fullname  5000 non-null   float64
 4   name==username        5000 non-null   int64  
 5   description length    5000 non-null   int64  
 6   external URL          5000 non-null   int64  
 7   private               5000 non-null   int64  
 8   #posts                5000 non-null   int64  
 9   #followers            5000 non-null   int64  
 10  #follows              5000 non-null   int64  
 11  fake                  5000 non-null   int64  
dtypes: float64(2), int64(10)
memory usage: 468.9 KB


In [8]:
data.isna().sum()

profile pic             0
nums/length username    0
fullname words          0
nums/length fullname    0
name==username          0
description length      0
external URL            0
private                 0
#posts                  0
#followers              0
#follows                0
fake                    0
dtype: int64

In [10]:
x = data.drop("fake", axis=1)
y =data["fake"]
x
import numpy as np
x=np.array(x).reshape(-1,1)
x
y=np.array(y)
y

array([0, 0, 0, ..., 1, 1, 1])

In [11]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
X_train

profile pic  nums/length username  fullname words  nums/length fullname  \
4227            0              0.428574               1              0.409561   
4676            0              0.463307               1              0.000000   
800             1              0.000000               2              0.000000   
3671            0              0.242633               1              0.000000   
4193            0              0.099566               1              0.000000   
...           ...                   ...             ...                   ...   
4426            1              0.297627               0              0.000000   
466             0              0.000000               1              0.000000   
3092            1              0.435895               1              0.000000   
3772            1              0.798867               1              0.002833   
860             1              0.000000               2              0.000000   

      name==username  description length  external URL  private  #posts  \
4227               0                   0             0        0       0   
4676               0                   0             0        1       0   
800                0                 119             0        0     234   
3671               0                   0             0        0       0   
4193               0                   0             0        0       0   
...              ...                 ...           ...      ...     ...   
4426               0                   9             0        1       6   
466                0                   0             0        0       0   
3092               0                   0             0        1      84   
3772               0                  12             0        0       3   
860                0                  16             0        0     819   

      #followers  #follows  
4227          73       432  
4676          16        81  
800         2318       160  
3671          55        45  
4193          31        87  
...          ...       ...  
4426         622       501  
466           15       595  
3092         104       172  
3772          75       167  
860         1163      3820  

[4000 rows x 11 columns]

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [17]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,

In [22]:
from sklearn.metrics import accuracy_score
print("accuracy_score :",accuracy_score(y_test,y_pred))

accuracy_score : 0.949
